/**
 * HOOPS Exchange STEP compatibility detection implementation.
 *
 * Detection algorithm (pure text scan — no OpenCASCADE needed):
 *
 * 1. Verify the file was generated by HOOPS Exchange (header keyword).
 * 2. Count every ADVANCED_FACE entity in the DATA section (total face count F).
 * 3. Locate the MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION entity.
 *    Its items list is  ('', ( #A, #B, ..., #Z ), #context )
 *    where the last item (#Z) is the base STYLED_ITEM for the solid and all
 *    preceding items are OVER_RIDING_STYLED_ITEM entities (one per face).
 * 4. Count entity references (#NNN) inside the items list → call this M.
 *    Covered faces = M - 1  (subtract the one base STYLED_ITEM).
 * 5. Uncovered faces = F - (M - 1).  Return that number (0 means no issue).
 */

#include "hoops_compat.h"
#include <fstream>
#include <iterator>
#include <TDF_Label.hxx>
#include <TDF_LabelSequence.hxx>
#include <TDF_ChildIterator.hxx>
#include <TDocStd_Document.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Shape.hxx>
#include <TopAbs_ShapeEnum.hxx>
#include <Quantity_Color.hxx>

namespace StepFixerNative {

int CountHoopsCompatFixes(const std::string& filepath) {
  // ---- read file -------------------------------------------------------
  std::ifstream file(filepath, std::ios::binary);
  if (!file.is_open()) return 0;
  std::string content(
    (std::istreambuf_iterator<char>(file)),
    std::istreambuf_iterator<char>());

  // ---- check origin ----------------------------------------------------
  // HOOPS Exchange always writes this string in the FILE_DESCRIPTION or
  // one of the early comment lines.
  if (content.find("HOOPS Exchange") == std::string::npos) return 0;

  // ---- count ADVANCED_FACE entities ------------------------------------
  // We count occurrences of "=ADVANCED_FACE(" which uniquely identifies
  // entity definitions (not references).
  int faceCount = 0;
  {
    const std::string needle = "=ADVANCED_FACE(";
    size_t pos = 0;
    while ((pos = content.find(needle, pos)) != std::string::npos) {
      ++faceCount;
      pos += needle.size();
    }
  }
  if (faceCount == 0) return 0;

  // ---- locate MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION --
  const std::string mdgrNeedle =
    "MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION(";
  size_t mdgrPos = content.find(mdgrNeedle);
  if (mdgrPos == std::string::npos) {
    // HOOPS Exchange file but no MDGPR at all — still needs a rewrite.
    return faceCount;
  }

  // ---- find the start of the items list --------------------------------
  // After the entity name + '(' we have: '',(items),#context)
  // We look for ",(" which separates the empty-string first arg from the
  // items-list second arg.
  size_t searchFrom = mdgrPos + mdgrNeedle.size();
  size_t commaOpen = content.find(",(", searchFrom);
  if (commaOpen == std::string::npos) return faceCount;

  // commaOpen points at ','; commaOpen+2 is the character after '('.
  size_t scanPos = commaOpen + 2;

  // ---- count # references in the items list ----------------------------
  // The items list contains only simple entity references "#NNN" and commas.
  // There are no nested parentheses inside the list itself, so a depth
  // counter of 1 (we just entered the opening '(') is sufficient.
  int itemCount = 0;
  int depth = 1;
  while (scanPos < content.size() && depth > 0) {
    char c = content[scanPos];
    if      (c == '(') ++depth;
    else if (c == ')') --depth;
    else if (c == '#') ++itemCount;
    ++scanPos;
  }

  // itemCount = (number of OVER_RIDING_STYLED_ITEM) + 1 (base STYLED_ITEM)
  // Faces covered by the MDGPR = itemCount - 1
  int coveredFaces = itemCount - 1;
  if (coveredFaces < 0) coveredFaces = 0;

  int uncovered = faceCount - coveredFaces;
  return (uncovered > 0) ? uncovered : 0;
}

void StripPerFaceColors(
    const Handle(TDocStd_Document)& doc,
    const Handle(XCAFDoc_ShapeTool)& shapeTool,
    const Handle(XCAFDoc_ColorTool)& colorTool)
{
  // Walk the entire XCAF document label tree.  Using only the free-shape
  // subtrees misses face sub-shape labels that XCAF places under assembly
  // component paths rather than the prototype solid path — which is exactly
  // what happens for assembly-wrapped files like slider4.  Iterating from
  // doc->Main() with allLevels=true catches them regardless of depth.
  for (TDF_ChildIterator it(doc->Main(), /*allLevels=*/Standard_True); it.More(); it.Next()) {
    TDF_Label child = it.Value();

    // Skip labels that don't correspond to a face sub-shape.
    TopoDS_Shape sub;
    if (!shapeTool->GetShape(child, sub)) continue;
    if (sub.ShapeType() != TopAbs_FACE) continue;

    // Remove all color types that might create OVER_RIDING_STYLED_ITEM.
    colorTool->UnSetColor(child, XCAFDoc_ColorGen);
    colorTool->UnSetColor(child, XCAFDoc_ColorSurf);
    colorTool->UnSetColor(child, XCAFDoc_ColorCurv);
  }
}

} // namespace StepFixerNative
